### ISSUE TITLE
how are preopened fds  numbered?

### ISSUE THREAD

**Issue by wanderer** [WebAssembly/WASI#10]
I'm confused on how preopened fds are numbered. The API doc currently says

```
As in POSIX, three file descriptor numbers are provided to instances on startup -- 0, 1, and 2, (a.k.a. STDIN_FILENO, STDOUT_FILENO, and STDERR_FILENO).

Other than these, WASI implementations are not required to allocate new file descriptors in ascending order.
```

So how do programs find the preopened `fds`?  Wasmtime currently seems to monotonically increment the `fd`s.  Should this be considered part of the spec?

**Comment by dumblob** [comment]
>So how do programs find the preopened `fds`? Wasmtime currently seems to monotonically increment the `fd`s. Should this be considered part of the spec?

Should it be allowed (for security reasons) for an application to find out which `fd`s were opened by other applications or just those `fd`s opened by the asking application itself?

**Comment by sunfishcode** [comment]
Currently they are numbered sequentially starting at 3. And currently WASI libc depends on this, in order to be able to discover the preopened capabilities. So yes, as long as this is how it works, we should add this to the spec and document it :-).

@dumblob Currently, in Wasmtime's implementation, the wasm application fd index space is distinct from the host process' fd index space, so applications can't observe which `fd`s are opened by other things in the same process.

**Comment by sunfishcode** [comment]
I've added some basic documentation for the pre-opened file descriptors here: https://github.com/CraneStation/wasmtime/pull/100

(I'm working on migrating the docs into the WASI repo, but for now this is where things are.)

**Comment by rylev** [comment]
@sunfishcode Should we close this as resolved?

**Comment by sunfishcode** [comment]
Yes, the original question here has been answered!
