### ISSUE TITLE
Prefer everything-is‑an‑object over everything-is‑a‑fragile-char‑stream-that‑has-to‑be‑parsed-with‑fragile‑regular‑expressions

### ISSUE THREAD

**Issue by ExE-Boss** [WebAssembly/WASI#153]
When&nbsp;**everything is&nbsp;an&nbsp;object**, its&nbsp;correctness can&nbsp;be&nbsp;statically verified&nbsp;by&nbsp;a&nbsp;compiler, and&nbsp;it&nbsp;won’t&nbsp;ever&nbsp;break due&nbsp;to&nbsp;the&nbsp;addition of&nbsp;a&nbsp;new&nbsp;property.

The&nbsp;same&nbsp;cannot be&nbsp;said&nbsp;when&nbsp;**everything is&nbsp;a&nbsp;fragile&nbsp;`char`&nbsp;stream _with&nbsp;no&nbsp;type&nbsp;information_**.

---

From&nbsp;what&nbsp;I’ve&nbsp;read in&nbsp;https://hacks.mozilla.org/2019/03/standardizing-wasi-a-webassembly-system-interface/, I’m&nbsp;worried that&nbsp;**WASI** might&nbsp;take the&nbsp;latter&nbsp;approach, which&nbsp;would&nbsp;be&nbsp;a&nbsp;mistake, since&nbsp;**WebAssembly** will&nbsp;eventually&nbsp;support [interface&nbsp;types](https://github.com/WebAssembly/interface-types).

**Comment by sunfishcode** [comment]
Since you mentioned that blog post, see also more recent posts in that series, which discuss both WASI and interface types.

Independently of that, WASI is already aligning to work well with interface types. As one example, the [witx file format](https://github.com/WebAssembly/WASI/blob/master/docs/witx.md#know-your-witx) is being designed to align with interface types where feasible. Similarly, the [handle](https://github.com/WebAssembly/WASI/pull/117) is one of our most fundamental concepts, and is also being aligned to work with interface types.

Byte streams will likely never go away entirely, because there will always be things in the outside world that we want to interact with which are bytes. But I agree that in general, we make the best use of wasm's strengths when we used typed interfaces rather than untyped sequences of bytes when we can.

I also want to mention our [phased development process](https://github.com/WebAssembly/WASI/blob/master/phases/README.md), which is designed to provide just enough stability to let people use the API today, but also give us the flexibility to make breaking changes and keep moving the overall API forward.

**Comment by sunfishcode** [comment]
Feel free to re-open or open new issues if you wish to add any further comments here!
