### ISSUE TITLE
Remove non-Core error constants

### ISSUE THREAD

**Issue by newpavlov** [WebAssembly/WASI#158]
Some error constants are used only in `libc` and can not emerge from Core functions. See this [comment](https://github.com/CraneStation/rust-wasi/pull/5#discussion_r315691452).

Continuation of bytecodealliance/wasi#7

**Comment by linclark** [comment]
Thanks for filing this. Once WASI modularization is complete, we'll be [refactoring the errors](https://github.com/WebAssembly/WASI/projects/1) so that each module only contains the errors that are relevant to its functions. Through that process, we will be cleaning up any unused errors, so I'm going to close this one out.
