### ISSUE TITLE
Terminal keyboard input support

### ISSUE THREAD

**Issue by sunfishcode** [WebAssembly/WASI#163]
Along with [ANSI escape sequences for display](https://github.com/WebAssembly/WASI/issues/162), we should also consider escape sequences for input, so that arrow keys, function keys, page-up/page-down/home/end/etc. can be used.

Assuming we take the approach in #162 of avoiding exposing the termcap/terminfo/TERM information to applications, it seems logical to the same thing for inputs, and just define escape sequences used by WASI, and have implementations translate into those sequences.

At the risk of being too cute, in the Unicode era, we could have quite descriptive sequences, something like this:

| Escape sequence | Meaning |
| ------------------------- | ----------- |
| ␛↑ | up arrow |
| ␛← | left arrow |
| ␛↓  | down arrow |
| ␛→ | right arrow |
| ␛⁽¹⁾ | F1 |
| ␛⁽¹²⁾ | F12 |
| ␛⌦ | Delete |
| ␛⎀ | Insert |

and so on, with "␛" here representing an actual ESC control character, so we can distinguish between the user entering a literal unicode symbol and pressing one of these special keys.

**Comment by sunfishcode** [comment]
Feel free to suggest better Unicode art for any of these, or for keys not covered yet!

FWIW, I looked at the circled numbers for function keys, but they only go up to ㊿, while terminfo function keys [go up to 63](https://pubs.opengroup.org/onlinepubs/007908799/xcurses/terminfo.html). Superscript digits give us as many function keys as we could want, though of course that's not the only way to go.

**Comment by programmerjake** [comment]
Why not just go all-out and do something like:
␛<b><i>\<JSON object></i></b>␤
(where ␛ and ␤ are the ESC and LF control characters)

and the JSON follows this template (derived from libSDL):
```javascript
{
    // a SDL_Scancode value
    // from https://hg.libsdl.org/SDL/file/bc90ce38f1e2/include/SDL_scancode.h
    "scancode": 1234,

    // a SDL_Keycode value
    // from https://hg.libsdl.org/SDL/file/bc90ce38f1e2/include/SDL_keycode.h#l34
    "keycode": 5678,

    // bitmask of modifiers -- SDL_Keymod value
    // from https://hg.libsdl.org/SDL/file/bc90ce38f1e2/include/SDL_keycode.h#l322
    "modifiers": 1024,
}
```

Even if we don't use JSON, please pick a representation that can handle all modifier combinations.

**Comment by mash-graz** [comment]
all this terminal related questions are in fact much more complex than expected.
sure, we usually just imagine only this very simple concept of direct key input resp. key code handling, as it perhaps had some relevance in good old DOS days, but on most modern systems it's a much more complex task, which is usually mediated/preprocessed/determined by a whole system of different infrastructure components. that's why it also needs more careful kinds of system control and configuration instaed of just key code or escape sequence filtering. 

just as an inspiration, you should perhaps take a look into this microsoft article series about the history and recent improvements of the windows console infrastructure: https://devblogs.microsoft.com/commandline/windows-command-line-backgrounder/ 

and there is also a nice introductory article available about the POSIX/linux side and all its mysteries: http://www.linusakesson.net/programming/tty/

if you are studding this writings, you'll immediately grasp, why the console handling interfaces look so different on both sides -- on this family, which has its roots in small compact PCs for local operation and in those other tradition, where remote access was more or less a requirement from day one on. especially the benefits of the latter approach can hardly be preserved, if we only provide an inadequate simple solution.

i wouldn't underestimate the complexity of this field. IMHO it makes much more sense, to just reuse the available infrastructure on the given systems and already available mature software components in a responsible manner (as also suggested in #161), instead of wasting to much energies by reinventing everything again (...and very likely trap into the same pitfalls as our predecessors ;)). sure, to some degree it's really necessary to make clear security related decisions to avoid obvious risks, but in general WASI shouldn't restrict or overly complicate the freedom and flexibility of practical utilization more than necessary.

**Comment by sunfishcode** [comment]
My sense in this issue is to consider just low-level terminal input, and not try to design a general-purpose input-event system. A general-purpose input system would be a valuable thing to have, but I think terminal input is a sufficiently distinct domain that we don't need to unify them. Assuming that's reasonable, we can go with something much simpler than JSON for terminal input.

An SDL-style scancode vs keycode distinction is a good idea, but for terminal input, I don't know of any situations where we have SDL-style scancode information, so my sense is that we don't need to include it here.

Using SDL code numbers, which are based on the USB keyboard spec, are also a good idea, though terminal input doesn't usually use SDL, and it doesn't receive hardware or raw OS input values, so it doesn't have a strong affinity here.

Modifiers: If we did go with Unicode symbols, we could represent modifiers with symbols too -- ⎈, ⎇, ⇧, prepended to the main character. However, as I research this domain more, I'm less excited about using Unicode here. It is nice if up-arrow on input can send the same sequence as move-the-cursor-up on output, and for output, we probably want to follow the established ANSI sequences for basic cursor movement and such.

**Comment by programmerjake** [comment]
One of the benefits of JSON is easy extensibility and wide programming language support. If we restrict ourselves to a single object where all members have C identifier names and integer values, it should be quite easy to parse for those who don't want to use a general JSON parser. We should specify that all unknown names should be ignored, except for `"version"` which if it is present indicates a future incompatible revision (with a version number as the value) and the whole keystroke should be ignored.

Example parser:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a528ef1e98dc0763c31b1618d5cfd997

**Comment by bjorn3** [comment]
Using json would cause excessive memory usage. For example if you want to paste 1mb of data into the terminal, that would send ~200mb of data to the program. All of which needs to be formatted and parsed again. It is also a lot of extra mandatory code. Using something binary like [`bincode`](https://docs.rs/bincode/1.2.0/bincode/) would be nicer, as it is easier to parse, because every field is at a fixed location, so you just transmuting the raw bytes to a struct is possible. It is also much more compact.

One problem with your current choice of fields is that it makes it impossible to paste characters without keyboard equivalent, like emoji and control codes.

**Comment by sbc100** [comment]
@bjorn3 I agree JSON seems rather excessive this use case.

(as does `bincode` BTW which looks like its designed for use cases where work is done to serialize / de-serialize.).

**Comment by programmerjake** [comment]
@bjorn3 JSON is only used for the things that don't have a normal UTF-8 representation (and for ESC itself), if the text you're pasting is UTF-8 without any ESC characters, then it can be sent to the input unmodified without increasing the input size. The JSON is only used instead of UTF-8 for keys like Ctrl+Shift+1 -- because that key combination doesn't have a defined UTF-8 representation.

**Comment by mash-graz** [comment]
i really share @sunfishcode's POV concerning this topic:

> An SDL-style scancode vs keycode distinction is a good idea, but for terminal input, I don't know of any situations where we have SDL-style scancode information, so my sense is that we don't need to include it here.

we simply have to differentiate between:

 * old fashioned POSIX-style  terminal resp. `stdio` based input
 * local machine and GUI system related keyboard handling

SDL and its data representation may be seen as nice cross platform solution for the later case, but it isn't a suitable example, how to handle the requirements and capabilities of the first category,

i don't think we should waste to much efforts on inventing another translation/representation of control commands. it's more important to understand their original function in controlling editing operations on the local terminal and generating out-of-band signals. but most of this terminal features became highly configurable over time and provide processing on the other side of the communication line as well. 

it's mainly this kind of **terminal IO configuration**, which i would see as the most important requirement, if we want to realize more satisfying input capabilities -- e.g. switch between (canonical mode)[https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap11.html#tag_11_01_06] and (non-canonical mode input processing)[https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap11.html#tag_11_01_07]

some of you may argue, that i'm too much focused on nothing else then this very old fashioned [POSIX terminal interface](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap11.html),
but that's done by purpose, because it's in fact this group of systems, where terminal io and CLI based work still has most practical relevance in real world. and those few exceptions, which do not fall into this category (e.g. windows and web based solutions like [xterm.js](https://xtermjs.org/)) usually provide very similar terminal control capabilities. that's why i still see a straightforward WASI POSIX termio configuration extension module as a more appreciable and much easier realizable and compatible solution than any more ambitious cross platform oriented compromise.

**Comment by sunfishcode** [comment]
I also think we can get by without a "version" field as well. The key events we're talking about here are described by terminfo and are very stable.

And more broadly, while the kind of extensibility that JSON would bring would have advantages, I also think the main value in adding functionality like this to WASI is in compatibility with existing terminals. Existing terminals don't have extensibility at this layer, so we wouldn't gain much by making WASI extensible at this layer either, And, we'd risk introducing complexity and new error conditions. So while I appreciate the ideas, I don't think JSON turns out to be a good fit here.

FWIW, I'm also leaning away from the Unicode approach I suggested at the top of this issue. While this is a space where vt100-family terminals in use today differ significantly, leaving room for WASI to potentially also do something different, using more traditional-style escape codes seems good enough, and will simply some implementations.

**Comment by abitrolly** [comment]
Linux terminal is absolutely horrible for all non-English users out there, because it doesn't transmit the keycode, so if you switch the layout, all shortcuts with letter keys stop working. As much as I like `vim` I just hate it when I need to edit anything in it in Russian.

Linux terminal is absolutely horrible for users of Desktop software, where you automatically use `Ctrl+S` to save you work. Imagine what Linux terminal does when you want to save you work with `Ctrl+S`? Its [acking freezes it](https://unix.stackexchange.com/questions/tagged/terminal?tab=Votes). And what people do when their app freezes is wait and close, losing the work they've tried to save.

Linux terminal has absolutely horrible latency. Because for the parser to distinguish between Esc key and any other key encoded with "Escape sequence", it needs to wait.

Linux terminal is horrible stateful mess. In other OS having a buffered queue of input events was a norm - in deterministic TUIs I pressed my keyboard piano and go preparing some tea while the app processes shortcut after shortcut. In Linux I am waiting for each key combination to finish before I start the next one. Because Linux terminal needs a pause to know if it is an Esc key I am pressed or F1. Linux terminal can also mess its own state, that's there is even a `reset` commands for users to clean up after it https://superuser.com/questions/122911/what-commands-can-i-use-to-reset-and-clear-my-terminal

The rhetorical question - do you really want to bring this ancient mess (which I admit was an extremely useful thing back in 1960s) into the post-COVID era to make people feel the pain as I felt it?

---

The bottom line - there is no other opportunity out there except in WASI to create an alternative 21st century protocol for (terminal) keyboard inpit, convenient for developers to debug and implement, with low latency, standardized physical key ids (because USB HID standard could not figure out how add pictures to their PDF you need to guess key names on your keyboard). The use cases should include all applications that now run in GUI, such as games, so that hot seat Mortal Combat in terminal could become possible.

If WASI implements a good keyboard interface/abstraction (I dk, `libinput`?), then implementing all the POSIX cruft as portability lib on top of that will not be a big problem. In the end the right name for Linux Terminal is already Linux Terminal Emulator, so no need to emulate emulator once more.

**Comment by sunfishcode** [comment]
I'm going to close this discussion here and post some updates to #161. As I mentioned [above](https://github.com/WebAssembly/WASI/issues/163#issuecomment-565659937) my original idea here of using Unicode symbols wasn't practical, and this issue doesn't contain a more specific plan, so we can close it and continue in #161.
