### ISSUE TITLE
Encoding module(JSON mainly?)

### ISSUE THREAD

**Issue by olanod** [WebAssembly/WASI#173]
Not sure if will ever be a goal of WASI to provide such high level interfaces but something like encoding/decoding common formats like JSON is a very common thing to do and would be great if it's provided by the environment saving some bits in the final WASM file by not having to ship my on JSON parser.

**Comment by sunfishcode** [comment]
It's possible. For APIs like this that can be easily implemented in pure wasm, what we'll want is for someone to build such a library and present it here. That will provide something concrete to discuss, and also a polyfill that engines can use rather than necessarily implementing it natively if we do standardize it.

**Comment by linclark** [comment]
The first step here is for someone to create a library outside of the standardization process to demonstrate the approach and gauge whether others find it useful. Since there's nothing actionable for the WASI team ATM, I'm going to close this one out for now. If someone does create this library and wants to discuss standardizing it, please do feel free to create a new issue.
