### ISSUE TITLE
Rust code gen question

### ISSUE THREAD

**Issue by nilslice** [WebAssembly/WASI#196]
Not a complaint or concern, just wondering if there is a plan to convert witx format `enum` values to Rust `enum` rather than the `pub const` values which are currently the translated results.

e.g.:
https://github.com/yskopets/envoy-wasm-rust-sdk/blob/master/envoy-abi/v1alpha/witx/typenames.witx#L7-L34 

is translated into:

https://github.com/yskopets/envoy-wasm-rust-sdk/blob/master/envoy-rust-abi/src/types_generated.rs#L9-L33

I'm _brand new_ to witx and just starting to poke around, read docs, etc... so forgive me if there are some major gaps on my end here!

**Comment by MarkMcCaskey** [comment]
One issue with using Rust enum values in FFI/untrusted contexts is that if it's passed as an argument, for example, and the guest gives the host a value out of bounds then it's undefined behavior.  So the host has to do a checked conversion every time and unless that enum ends up interacting with a lot of safe Rust or is used in places that strongly benefit from Rust enums, like exhaustive matching, then in my experience it's simpler to just use constants.

So it's probably still useful to generate them because I can see it being valuable for the smaller enums, but people using the bindings from Rust need to be aware that it's not safe to use them directly anywhere that's exposed to untrusted input.

**Comment by sunfishcode** [comment]
At the WASI API level, the main concern is that we don't want WASI APIs to exhibit [undefined behavior if someone passes in an unrecognized value](https://doc.rust-lang.org/reference/behavior-considered-undefined.html). We want WASI to have defined semantics for those cases, and at least plain Rust enums don't allow us to do that.

It's possible that some combination of `repr(C)` and `non_exhaustive` or other things could cause Rust enums to behave as WASI needs here; if someone who knows the Rust semantics in detail wanted to help us figure out what we need here, that'd be great.

The other side of it is that we don't expect many users will be programming to the raw WASI APIs directly. Most users should be using Rust's libstd or WASI libc or other libraries which all offer friendlier APIs. Ergonomics are useful, even at low levels of the system, but

**Comment by nilslice** [comment]
TIL! Thanks @MarkMcCaskey, @sunfishcode. 

To support higher-level crate design, my assumption is that it would be fully acceptable to hand-map a generated rust const from the witx types to a Rust enum variant, assuming c-like enums are used where their numeric value matches the generated const value? 

> It's possible that some combination of repr(C) and non_exhaustive or other things could cause Rust enums to behave as WASI needs here; if someone who knows the Rust semantics in detail wanted to help us figure out what we need here, that'd be great.

As I do more research and come up to speed here I would be glad to offer some suggestions. This work and progress thus far is super exciting! Kudos to you all for getting this out there.

**Comment by sunfishcode** [comment]
Yes, that would work. It's also worth pointing out that WASI isn't API/ABI-stable yet -- we have snapshot versions, and within a version things are stable, but there are changes between versions, and this is another reason why it's better for most users to use higher-level abstractions, which hide these details.

**Comment by nilslice** [comment]
Understood. Thank you very much for the detail!
