### ISSUE TITLE
How to configure environment to compile C/C++ program with non standard libraries?

### ISSUE THREAD

**Issue by newbee1920** [WebAssembly/WASI#207]
Could you write some instruction? Or is there an existing link for that instruction?

**Comment by hackingotter** [comment]
I did this using the WASI-sdk. I included the glibc as normal but then compiled using the -c flag (compile only, no linking). For example printf then shows up as an import.

**Comment by saghul** [comment]
This can be useful: https://github.com/wasienv/wasienv (not affiliated, just a happy user)

**Comment by sunfishcode** [comment]
@saghul WASI as a whole will be better off in the long run if we work to make the underlying tools better.

@newbee1920 wasi-sdk's `clang` supports the usual `-L` and `-I` flags for specifying directories to find libraries and include files. Can you say more about what you're looking to do?

**Comment by saghul** [comment]
I don't really have a horse in this race... doesn't wasienv provide exactly that? Or do you mean that each specific tool would get "WASI enabled" ?

**Comment by sunfishcode** [comment]
wasienv is wrapper scripts around wasi-sdk, outside of the WASI umbrella. If there are specific things you'd like to do that wasi-sdk doesn't support, please file issues on wasi-sdk and work with us to make the actual tools better, rather than papering over them with wrapper scripts.

**Comment by saghul** [comment]
Ah, I see now, good point. I guess it's up to the authors to reach out. I've been happily using both wasienv and the plain SDK.

An interesting thing is bootstrapping: how does one get ahold of the SDK? Going to GH releases is arguably not very ergnomic. So there is a need for, at least, that: an "automated" way to install the WASI SDK. wasienv provides that.

**Comment by sunfishcode** [comment]
There isn't any fundamental reason why wasi-sdk doesn't have friendlier packages and landing pages; it's just a matter of people and resources. If you're interested in helping, I'd be happy to talk about what might be done. If having such things sooner rather than later is worth promoting an ecosystem where the foundations are split between actual tools and wrapper scripts maintained by independent projects, wasienv may be for you.

**Comment by sbc100** [comment]
I think one thing we could do is try to fix https://github.com/CraneStation/wasi-sdk/issues/58 so that users don't need to pass `--sysroot` to clang.  IIUC this is one thing that wasi-env does that wasi-sdk doesn't.

I've been being to try and make this work in upstream clang... failing that we could a wrapper scripts ourselves to the wasi-sdk to add this flag (and anything else what wasi-env is doing).

**Comment by newbee1920** [comment]
> @saghul WASI as a whole will be better off in the long run if we work to make the underlying tools better.
> @newbee1920 wasi-sdk's clang supports the usual -L and -I flags for specifying directories to find libraries and include files. Can you say more about what you're looking to do?

We are trying to use boost c++ libs but not sure if wasi sdk supports them.

**Comment by sunfishcode** [comment]
@newbee1920 wasi-sdk should support Boost libraries that don't depend on C++ exceptions; please file issues if you find anything that isn't supported. wasi-sdk's clang supports the usual -L and -I flags for specifying directories to find libraries and include files.
