### ISSUE TITLE
Function error code acces or access?

### ISSUE THREAD

**Issue by denisvasilik** [WebAssembly/WASI#209]
I just wondered whether the function error code should be named **access** rather than **acces**?

**Comment by kubkon** [comment]
Yeah, that's a remnant from POSIX (there, it's called `EACCES`). Personally, much like in case of `oflags::creat` (see #199 for reference) we don't really save much in terms of the encoding, so I'd be keen to vote in favour of having `errno::access`. :-)

**Comment by denisvasilik** [comment]
I see `oflags:creat` is another one. May be it makes sense to generally discuss 
naming conventions for WASI and put the result into the design principles document.
Personally, I think this is where WASI should distinguish itself from POSIX a bit. 
For this issue, I'm just going to create a pull request. Let's see what happens :)

**Comment by sunfishcode** [comment]
The PR to rename `acces` to `access` is now merged! And `creat` is already renamed to `create` on the ephemeral branch.

If people are contemplating broader renaming efforts, please file new issues so that we can discuss them before doing the actual work. So far, renaming has been limited to roughly "abbreviations which look wrong rather than looking like abbreviations", so if we're going to expand the scope, we should talk about it first :-).
