### ISSUE TITLE
Reference types in C/C++

### ISSUE THREAD

**Issue by tlively** [WebAssembly/WASI#219]
I have been thinking about the possibility of supporting reference types in C/C++ as values that can be passed as parameters, returned from functions, and stored in local and global variables, but cannot be address-taken, stored in arrays or structs, or stored in memory.

I am curious to gather thoughts from the WASI community about how such source-language reference types might be used. Their immediate benefit would be that low-level code that interfaces with WASI APIs that receive and return capabilities could be written in C/C++ rather than hand-written assembly, but I am interested in hearing how application developers would use reference types in their application-level code as well. Let me know what you would do with first-class reference type support!

**Comment by sunfishcode** [comment]
As WASI expands into areas not covered by POSIX, it will have a need for new application-facing APIs. The ability to define those APIs in terms of references rather than integer indices is very attractive. So yes, if you add the ability to pass and return references to C/C++, in a way that works with wasi-sdk and doesn't depend on JS, that would be very useful!

**Comment by linclark** [comment]
This is now being implemented in clang, so I'm going to close this out.

**Comment by tlively** [comment]
Thanks, @linclark!
