### ISSUE TITLE
Everything as a URL?

### ISSUE THREAD

**Issue by unmellow** [WebAssembly/WASI#223]
[redox's](https://doc.redox-os.org/book/design/url_scheme_resource/everything_is_a_url.html) approach to there API is "everything is a URL".
an example they showed is to run a command on the file foo/bar.
you type file:/foo/bar. 
they explain that [here](https://doc.redox-os.org/book/design/url/urls.html). and show the other schemes they have [here](https://doc.redox-os.org/book/design/scheme/schemes.html).
my main reason for suggesting this is that WASI is WEBassembly's system interface
and the web as I've been told before is built on the hyper link
I am not knowledgeable enough to come up with any more reason's to do this so that's it

**Comment by unmellow** [comment]
one thing you could do on top of this, 
is allow people to explicitly give certain wasm reactor's control over a scheme also, 
reactor's shouldn't decide or even know what the name of there scheme is to other apps, 
they should just deal with the input as they get it also,
to keep with the wasm can't do anything by default model
scheme's and the substructure's like with filedescriptor's now must be explicitly provided to
other modules too

**Comment by sunfishcode** [comment]
It's a fun idea.

At an application level though, the direction WASI is heading is away from "A passes B a string, then then B opens the resource", and toward "A opens the resource and passes B a handle". In both cases, B ends up with ability to mostly transparently access resources either through files or network connections. But with handles, we separate the *acquisition* of new resources from the *use* of the resources, which lets us bring acquisition closer to the user, who knows where their files are and how to open them, and further away from the application, which doesn't usually need to care.

User-facing code may then choose to offer everything-is-a-URL abstractions as part of the User Interface, but it'll be a UI concern, rather than a property of the system as a whole.

**Comment by sunfishcode** [comment]
The original question is answered; feel free to re-open or open new issues if there are further questions!
