### ISSUE TITLE
Are `args_get` and `environ_get` calls read-only wrt to their args?

### ISSUE THREAD

**Issue by kubkon** [WebAssembly/WASI#232]
As in the title, do we expect `args_get` and `environ_get` syscalls read-only wrt to their args (i.e., pointers into guest memory)? Currently, as far as I can see, across all snapshots, both accept `(@witx pointer _)` whereas I'd expect them to be `(@witx const_pointer _)`. The former implies that we could potentially write contents to the passed in memory locations (I think!). Thoughts?

cc @sunfishcode @pchickey

**Comment by kubkon** [comment]
I think I was looking at it the wrong way round. We need mutable pointers so that we can pass the args and environ to the guest, and not the opposite. Ótherwise, `args_sizes_get` syscall wouldn't make much sense :-)

**Comment by sunfishcode** [comment]
Yeah, the top-level pointer needs to have mutable pointees. The inner pointer is another matter.

While `T*` implicitly converts to `const T*`, `T**` doesn't implicitly convert to `const T**`, because if it did, you could get a `const T*` and put it in an array pointed to by a `const T**` converted from a `T**`, and then use the original `T**` to get a `T*` back out, and strip away `const` without a cast.

So we leave the inner pointer as non-const, not because we need to mutate anything through the pointers, but because we don't want to require callers from needing a cast if *they* want to mutate something through the pointers later on. The most common thing to do with these pointers is to pass them to `main` as `argv`, and C requires "[...] the strings pointed to by the `argv` array shall be modifiable by the program" (5.1.2.2.1p2). So we leave them non-const.

**Comment by kubkon** [comment]
> Yeah, the top-level pointer needs to have mutable pointees. The inner pointer is another matter.
> 
> While `T*` implicitly converts to `const T*`, `T**` doesn't implicitly convert to `const T**`, because if it did, you could get a `const T*` and put it in an array pointed to by a `const T**` converted from a `T**`, and then use the original `T**` to get a `T*` back out, and strip away `const` without a cast.
> 
> So we leave the inner pointer as non-const, not because we need to mutate anything through the pointers, but because we don't want to require callers from needing a cast if _they_ want to mutate something through the pointers later on. The most common thing to do with these pointers is to pass them to `main` as `argv`, and C requires "[...] the strings pointed to by the `argv` array shall be modifiable by the program" (5.1.2.2.1p2). So we leave them non-const.

Makes sense, thanks!
