### ISSUE TITLE
WASI Logo

### ISSUE THREAD

**Issue by lachlansneff** [WebAssembly/WASI#3]
I noticed that WASI needed a logo, so I'm proposing this one:

<img src="https://user-images.githubusercontent.com/31360811/55445325-9c171500-556f-11e9-8ef6-1c86056f9880.png" width="200">

I'd love to hear what people think and am happy to make alterations!
A zip file containing this image in SVG format is attached.

[Slice.svg.zip](https://github.com/WebAssembly/WASI/files/3036402/Slice.svg.zip)

**Comment by sunfishcode** [comment]
You may have missed the [existing logo](https://github.com/WebAssembly/WASI/blob/master/WASI.png), which is [prominently featured](https://github.com/WebAssembly/WASI) in this repo since the [first commit](https://github.com/WebAssembly/WASI/commit/3991c0e0c4ae71f78ef6441b8cc05f5138d4b1e9#diff-e6bbce60a5f2470dbf07e5b0d0d26d5b) and which was present at the time of the initial WASI announcement [in](https://wasi.dev/polyfill/) [several](https://github.com/CraneStation/wasi) [places](https://wasi.dev/).

I do appreciate the sentiment, but for now, I would like to focus on the technical work at hand. We still have many big-picture questions to answer. It will be better to design a new logo once the overall character of the system is better understood.

**Comment by appcypher** [comment]
If that's the case, shouldn't this issue remain open?

**Comment by syrusakbary** [comment]
I think WASI is in a place right where an improvement on the logo could help on increasing adoption by some fraction. I also think we already had some time to understand the system as a whole.

Because of that, it might be good to research into new logos and perhaps even create a contest where more people can participate.
If this is too much overload for others, I'm happy to take on the responsibility of organizing it.

Can we decide on what a step forward for the WASI logo? Also, could we keep this issue opened until we decide? Thanks!

cc @sunfishcode @tschneidereit @pchickey @alexcrichton @sbc100

**Comment by devsnek** [comment]
it was a good three or four years before we voted on a wasm logo. i don't see why this needs to be rushed.

**Comment by syrusakbary** [comment]
> it was a good three or four years before we voted on a wasm logo. i don't see why this needs to be rushed. i think marketing should be held off until we know what we're trying to market.

I don't mean to rush things, sorry if my message got misinterpreted.
Logos can be iterated, and we can iterate on the logo as time progresses as well :) 

@devsnek any reason on why you don't think is a good idea to do a first iteration on the logo now that WASI is getting more attention?

**Comment by appcypher** [comment]
@devsnek we are not saying the decision be made immediately, instead this issue should remain open and contributions welcome, just like it was with the wasm logo.
https://github.com/WebAssembly/design/issues/112

**Comment by syrusakbary** [comment]
It seems that more people are adopting this logo proposal.
https://twitter.com/sjoerd_during/status/1317156210139947008

It's quite tiring that all Wasmer attempts to collaborate into WASI are being halted without any discussion.

**Comment by sunfishcode** [comment]
If I've ever halted anyone's attempts to collaborate in official forums, please bring it to the attention of the CG chair.

As @devsnek notes, WebAssembly itself went a few years without an official logo. Logos aren't listed in the WebAssembly CG's deliverables, so decisions were left to the chairs. The chairs made a choice early on to focus on the tech and avoid the distractions of logos. During that time, people wrote blog posts, gave talks, and even printed stickers using various unofficial logos. Later, the chairs came up with a process for picking an official logo, a new logo was chosen, and then everyone switched to using the new logo for their blog posts and talks and everything else. Despite all this, WebAssembly seemed to do ok.

We are aiming for WASI to be part of the foundation of a long-lived ecosystem. As WebAssembly itself showed us, we don't need to rush things like logos. With all the distractions many of us have in our personal lives, right now is not a great moment to take on additional distractions.

**Comment by syrusakbary** [comment]
Facts weight more than words, and the fact that this issue remains closed is just another indicator of what I mentioned. Regardless of any analogy, the [Wasm logo thread](https://github.com/WebAssembly/design/issues/112) was only closed once a logo was selected.

> If I've ever halted anyone's attempts to collaborate in official forums, please bring it to the attention of the CG chair.

I don’t think we should point fingers to anyone. However more actors in the ecosystem are aware of what I mentioned, so contacting the CG chair would probably lead to a more productive discussion. Who should I contact? (I’m unaware of who is the chair of WASI)

**Comment by devsnek** [comment]
> the Wasm logo thread was only closed once a logo was selected.

This issue asked for feedback on a specific design, not for submissions.

**Comment by tschneidereit** [comment]
> Who should I contact?

That depends on what kind of conversation you want to have, exactly.

a) Do you think specific decisions should be revisited?
b) Do you want to try to get aspects of the subgroup’s process changed?
c) Do you want to raise concerns about adherence to the WASI subgroup’s process?
d) Do you want to lodge a complaint about an individual’s behavior?

**For a)**, changes, sometimes slight ones, to the engagement style can make a big difference in how much traction your topics are getting, and whether you’re able to get support for proposed changes.

If you’d like to make a more fully developed case for a particular change, you can create a presentation for the bi-weekly meetings. That’s probably more worthwhile for any technical issues where you feel like you’ve been blocked, and a more thorough conversation with higher bandwidth could help.

**For b)**, a presentation at a WASI subgroup call on which aspects you think should be changed, and how those changes are motivated, would be a good first step.

**For c)**, if you think the WASI subgroup doesn’t adhere to the processes of the WebAssembly CG, then a discussion within the subgroup as described above would perhaps still be the right approach, but an escalation path would be to make a case directly to the subgroup chairs, which would be @sunfishcode and @sbc100, or the CG chair, @binji.

**For d)**, if you think you need to file a complaint about specific actions individuals took, then there are two main cases to consider: whether you want to report a CoC violation or not. In the former case, the Wasm CG has [documentation on how to proceed](https://webassembly.org/community/code-of-conduct/).

If the complaint isn’t about CoC violations, then the subgroup or CG chairs would probably still be the right people to reach out to.

**Comment by syrusakbary** [comment]
> This issue asked for feedback on a specific design, not for submissions.

I'm not a native english speaker and perhaps I haven't read properly in between lines.
But after re-reading this whole thread it was implied that submissions were not even of interest.

I also [proposed a submission mechanism](https://github.com/WebAssembly/WASI/issues/3#issuecomment-541976366) in this thread exactly one year ago:

> Because of that, it might be good to research into new logos and perhaps even create a contest where more people can participate.
> If this is too much overload for others, I'm happy to take on the responsibility of organizing it.

And the response is literally the same (non-existent and the ones that addressed didn't try to help on creating a path forward other than dismissing our need for improving the logo).

-----

For such a simple thing we are trying to push forward: let's see what we can do to improve the WASI logo.
It feels that the steps on how to do it were never clarified in this thread, we have to wait a year to get a response and still not making any progress.

Things should be easy, it definitely doesn't feel that way.

**Comment by linclark** [comment]
I [commented on your PR](https://github.com/WebAssembly/WASI/pull/337#issuecomment-713048466), but I think the risk I raised is important enough to reiterate here.

We would need to work with a lawyer to determine the IP issues around this. It’s possible that just using the same policy as for the WebAssembly logo works, but I know that various organizations have grown more concerned about IP in this space since then.

This is in no small part because your company, Wasmer, attempted to register “WebAssembly” and “Wasm” as trademarks. The [USPTO rejected the application](https://tsdr.uspto.gov/documentviewer?caseId=sn88703780&docId=OOA20200227112217#docIndex=3&page=1), but I don’t think we can assume that attempts to register a brandmark for a WASI logo would be similarly rejected. 

We need to consider the community’s long term best interests in any decision like this. If a single company were to acquire the trademark to WebAssembly, I believe that would be actively harmful to the community. I think the same applies for the brandmark rights to the WASI logo. 

Given the context, adopting a new logo would require a good amount of work on the part of the chairs—we need legal advice on what the IP policy should be, and the chairs would have to organize that. I think this is too much of a burden to put on them for something that is currently so limited in its impact.

**Comment by syrusakbary** [comment]
Thanks, since is reiterated here I feel it's also good to write here my response. Hope that's ok.

> We would need to work with a lawyer to determine the IP issues around this

Happy to offer a copyleft version of any logo proposed by Wasmer. I believe that shall solve the IP concerns around it.
The goal of pushing the logo forward is not having a company to own it and sue other companies on its usage. The goal is to increase de adoption of WASI.

> This is in no small part because your company, Wasmer, attempted to register “WebAssembly” and “Wasm” as trademarks. The USPTO rejected the application, but I don’t think we can assume that attempts to register a brandmark for a WASI logo would be similarly rejected.

There is much more context than what is presented, and I'll do my best to shed some light on it.

The trademark requests were driven by our lawyers.
After getting contacted from someone in the community a few months ago, we reached them and decided to not pursue that path. This has nothing to do with the request for changes in the trademark request from USPTO (which was not a rejection), as we could have still pursued and owned the trademark after... (see Oracle owning the Javascript trademark).

We have decided this path even if it could be specially harmful for us in the long term in the case an organization like the Bytecode Alliance owns it in the future... why? Because of they have already veto-ed our intention to join based on personal and/or racial bias... trying to favor an ecosystem where Wasmer (the company) is out of the picture (sad, but true).

I think is important to note the following because some times is very easy to assume wrong intentions from players in the industry, specially if it fed into an argument that favors specific products (unfortunately it's been happening quite a lot for us):

The success of Wasmer as a company is highly tied to the success of WebAssembly as a technology. Therefore is in our best intentions to assure the long-term success of it, as well as accelerate it's adoption as much as we can on the short term.

------

We are the underdog here. I'd really appreciate if rather than fighting we could work together and make of WebAssembly and WASI a much more welcoming place, although I realize that's no longer in my hands.

**Comment by linclark** [comment]
> Because of they have already veto-ed our intention to join based on personal and/or racial bias... trying to favor an ecosystem where Wasmer (the company) is out of the picture (sad, but true).

The rejection from the Bytecode Alliance was based on a history of behavior that isn’t compatible with the BA codes of conduct—both the individual CoC and the organizational CoC.

We made both of these points explicit in the rejection email. In that email, we also said that if Wasmer established a track record of positive engagement, we would re-evaluate.

Before you respond, I’d suggest not spamming people who are subscribed to this repo. This is not the right forum for an appeal of BA decisions. If you believe BA members are unfairly blocking your efforts in any WebAssembly CG projects, I suggest that you escalate the issue to Wasm CG leadership.

**Comment by syrusakbary** [comment]
It's noteworthy that you wanted to make your point clear in this thread (we could have continued the discussion in much better places) but somehow an answer from my side implies spamming.

Besides that, I agree with you. This is not the best place to discuss about the personal and/or racial bias that the Bytecode Alliance has demonstrated so far.
Let's keep this thread to discuss a way forward for the WASI logo.

**Comment by caspervonb** [comment]
What is the license of that svg file @lachlansneff? published anywhere with a license attached? would like derive from it for wasi-test, web-wasi et cetera 🙃

**Comment by syrusakbary** [comment]
Today we had the [WASI CG meeting](https://github.com/syrusakbary/WASI/blob/master/meetings/2020/WASI-10-22.md) - [transcription here](https://docs.google.com/document/d/1uGgt-M6iHUzXTYk8Uuc5dohJ0EIwWft_Kz9aFuQi2zI/edit). I explored the issues of the current logo, namely:
* **Unmatched font kerning**
* **Not digitally accessible**: not WCAG compliant
* **Unmatched font styles & weights**
* **Non-squared**: 50% wasted empty space

The slides I presented at the community meeting are now public, so feel free to go through it if you want to research the issues in more detail:
https://speakerdeck.com/syrusakbary/wasi-logo-proposal

We also explored some other options for the logos.
By the end of the meeting it was mentioned the risks of IP (Intellectual Property) of a new logo: I briefly talked with lawyers and they mentioned that a Creative Commons or Copyleft license will avoid issues regarding IP and will in fact be much better than the current situation (a logo with no explicit license at all).

After finishing the presentation the WASI CG decided with no opposition to **fix the current issues while deviating the minimally possible from current logo, preserving its style** (as it was much easier to do than adopting a logo such as presented in the header of this issue)

-----

As such, I've been working with designers to make a high-quality icon that will solve this aforementioned issues, along with bringing it with a svg-version.

After a few iterations we are now happy with the result (given the mentioned constraints), as it greatly improves readability which is critical for accessibility for low-vision people.

<p align="center"><img src="https://user-images.githubusercontent.com/188257/96919511-bae64080-1460-11eb-9e9e-e9c3c409660c.png" width="312" /></p>

Here are the main differences:
* **Font kerning**: is now uniform
* **Font color**: "SI" is now white
* **Font styles**: matched between "WA" and "SI"
* **Purple color**: The purple Wasm icon is the closest Pantone color: [Pantone 7442 C color](https://www.pantone.com/color-finder/7442-C). This will bring uniformity when printing professionally.
* **SVG format**: the icon now can be easily scaled to any size

Following the proposal for the Wasm icon, we have created a public repo (happy to transfer it to the WebAssembly Github org if that would be useful):
https://github.com/syrusakbary/wasi-logo


To minimize the work required from other people in the committee or community, I'll follow-up with PRs once any feedback or concern is addressed for this draft icon, updating the logo in:
* WASI website
* WASI repo

**Comment by ttraenkler** [comment]
The vision and people behind WASI are a source of inspiration to me. I would love to see this thrive and become a reality and the inventors and contributors being acknowledged. Given the size of the vision and the limited resources I hope to help uniting the small community in this uncertain early stage. I see concerns about logo design and ownership being a distraction from the conceptual work in this early stage and a bigger trust issue clouding the actual issue. Interpreting written words is a delicate issue and I assume good intentions. 

Assuming the concern is not about taking ownership and the actual issue just making the existing logo more sound with minimal changes (which I can see from a perceptual perspective): If it finds consensus, as a neutral party I would offer to donate the copyright to the following proposal to the WASI group or the most suitable body as seen by the original inventors. I have no interest in holding the ownership and no active business with Webassembly, just doing voluntary community work. If it helps resolving the issue or even help rebuilding trust between parties and move the focus back to the shared vision behind the technology, this is all I hope for.


<img width="463" alt="Bildschirmfoto 2020-10-23 um 20 33 56" src="https://user-images.githubusercontent.com/347722/97045372-eeff5580-1575-11eb-88ad-25091b87e36d.png">
© 2020 Thomas Tränkler

**Comment by sunfishcode** [comment]
Something that is not apparent from the public WebAssembly logo issue is that logo contests are a lot of work to organize.

I urge everyone to please hold off with logo submissions at this time.

WASI is just getting started. There are many things we don't even know about what WASI's personality will be.

The current logo will not be the last word. We will find a new logo some day.

Please don't oblige us to spend yet more time at this moment focusing on logos.

Thanks.

**Comment by ttraenkler** [comment]
Acknowledged, thanks.

**Comment by syrusakbary** [comment]
@sunfishcode just to be explicit and clear, which I think is always good:

My last message (with the WASI logo minimally fixed) is a response to what we agreed to do in the WASI meeting: fix the current logo issues while minimally deviate from current concept.

If no one has feedback I'll create the corresponding PRs so we can move on asap with the current (and non-final) logo :)

----

Great work on the logo @ttraenkler!
In the WASI meeting we decided to delay the logo contest once the scope of WASI was clearer. So once we open the contest for the WASI logo in the future, it will be a great option to consider!

**Comment by linclark** [comment]
Following up from the last meeting:

As @sunfishcode said, he has spent some time looking into the potential legal issues that I mentioned above, but still has unanswered questions. I’m taking this over to allow him to focus on other important issues.

I have reached out to a colleague who has relevant experience. I expect that he'll be able to give me a clearer understanding of any nuances in the law as pertains to this. I will report back here once we’ve had a chance to get final confirmation that there are no potential issues.

**Comment by syrusakbary** [comment]
I just randomly stumbled upon this issue again... and realized that no action has been taken Since Dec 2, 2020 (more than 2 years ago), even though a report was promised then ("I will report back here once we’ve had a chance to get final confirmation that there are no potential issues").

Just for clarity for future readers, this is the logo that WASI had since 2019 that we haven't been able to improve for 4 years:
![](https://raw.githubusercontent.com/WebAssembly/WASI/23a52736049f4327dd335434851d5dc40ab7cad1/WASI.png)
