### ISSUE TITLE
Is WASI already usable on Android?

### ISSUE THREAD

**Issue by bbigras** [WebAssembly/WASI#302]
Any guides on how to use WASI on Android?

I'm wondering if I could use some python code just like some C lib on Android with WASI.

**Comment by sbc100** [comment]
If you just want to run python on android the simplest way would be to simply build cpython for android using NDK.   

Compiling cpython to WASI and then building a WASI runtime for android might be possible but it would be a *lot* more work.  Also, many python features would simply not work in WASI due to limits number syscalls available.  (e.g. threading, subprocess, ctypes).

**Comment by bbigras** [comment]
> If you just want to run python on android the simplest way would be to simply build cpython for android using NDK.

Gotcha. Thanks!

> Also, many python features would simply not work in WASI due to limits number syscalls available. (e.g. threading, subprocess, ctypes).

That's Android limitations right? Would I have those limitations on Linux?

**Comment by caspervonb** [comment]
> That's Android limitations right? Would I have those limitations on Linux?

Limitation of the ABI, we only provide syscalls for filesystem i/o, clocks, and some miscellany.

**Comment by bbigras** [comment]
I see. Thank you very much.

**Comment by cjihrig** [comment]
FWIW, I believe the [wasm3](https://github.com/wasm3/wasm3) engine runs on Android with WASI support. I haven't tested it personally though.
