### ISSUE TITLE
WITX format specification

### ISSUE THREAD

**Issue by promethe42** [WebAssembly/WASI#309]
Hello,

Since I would like to create a WITX RPC adapter, I would like to transpile WITX specs into network/serialization enabled WASM modules that will plug on top of the actual WASM module that implements the WITX interface. This ways, any WITX-powered WASM module could become RPC capable.

The first transport layer would be HTTP2, with the possibility to add others later. I don't know yet about serialization, but probably something simple to do in Rust since that's the language I intend to use to create those WASM adapter modules.

The [witx crate](https://crates.io/crates/witx) says it's meant to "Parse and validate witx file format".
But I could not find the said specification for the WITX file format.

Did I miss something? Can you please a formal format specification for WITX?

Regards,

**Comment by sbc100** [comment]
Did you see this document: https://github.com/WebAssembly/WASI/blob/master/docs/witx.md

Basically witx is based on WIT which itself is based on WAT.    The WITX specific extensions to those other formats are fairly small.

**Comment by promethe42** [comment]
Yes I found it. But my understanding is that WAT is the format for the
whole of WebAssembly.

How can I know what's WITX (and what's not) in the WAT specification?

**Comment by sbc100** [comment]
You need to look at WIT first.  This is WebAssembly interface types, which WITX is based on.  Sadly the link to the module types proposal is stale, it looks like that proposal got renamed perhaps.   The summary is that WIT (WebAssembly Instance Type) is a subset of WAT which just contains the imports and exports of a given module.     So there are no function definitions and no instructions to pass which makes a it quite a bit simpler than full WAT.   

It sounds like we need to fix that like to WIT format and that might make things more clear?

**Comment by promethe42** [comment]
If by WIT you mean this spec:

https://github.com/WebAssembly/module-linking/blob/master/proposals/module-types/Overview.md

Then I'm affraid it leads to a 404.

Is [this](https://github.com/WebAssembly/module-linking/blob/master/proposals/module-linking/Binary.md) the right documentation for WIT?

**Comment by promethe42** [comment]
What I'm trying to implement is a `#[wasm_export]` macro to generate a static `*u8` that will contain the WITX declaration for the function.

So the following Rust code:

```rust
#[wasm_export]
fn add(a: i32, b: i32) -> i32 {
    a + b
}
```

Would become:

```
#[no_mangle]
pub static __ADD_WITX: StaticCString = StaticCString(b"THE_WITX_DECL_GOES_HERE\0" as *const u8);

#[no_mangle]
extern "C" fn add(a: i32, b: i32) -> i32 {
    a + b
}
```

Then I could write a WebAssembly loader that:

1. Loads the WASM module.
2. Finds such WITX declarations.
3. Exposes the corresponding functions (`add()` in this case) as an RPC method.

**Comment by sbc100** [comment]
Yes I believe module linking is the evolution of the old instance types proposal.  

Its kind of shame because I think module linking is a superset of the old instance types.    @lukewagner what do you think, is it worth specifying instance types as a subset of module linking so that WITX can be specified more simply?

**Comment by sbc100** [comment]
The existing WITX users I believe do this the other way around.  i.e. define you WITX interface once and then use static code generators to generate you rust/C/C++ binding.   See https://github.com/WebAssembly/wasi-libc/tree/master/tools/wasi-headers.   

It looks like perhaps you trying to do the opposite and instead generate at WITX interface from rust source code?  Is that right?

**Comment by promethe42** [comment]
> It looks like perhaps you trying to do the opposite and instead generate at WITX interface from rust source code? Is that right?

My goal is to expose functions from any language as a WITX interface available in the WASM module, so WASM modules can talk to each other.

Since Rust as very good support for WASM/WASI - including crates to open and explore WASM modules - I thought I would start with Rust. But I would like to do the same for Python using annotations for example. So a WASM module built from Python would be able to call methods from a WASM built from Rust. And that "call" could be RPC enabled, with battery included for HTTP2 + (de)serialization of the call+types.

The goal is *not* linking strictly speaking. The goal is distributing calculations as WASM modules that can call each other over the network/IPC. A bit like FaaS but with native interfaces directly in the programming language, and the RPC glue automagically generated by a single dynamic loading WASM module that read the WITX and exposes it.

**Comment by sbc100** [comment]
If you are generally trying to achieve inter-module calls or RPC between modules, I don't think you need WASI.   You can either just use raw wasm types or follow the interface types proposal:  https://github.com/WebAssembly/interface-types/blob/master/proposals/interface-types/Explainer.md,  Interface types is specifically about allowing higher level types such as strings to be communicated between different languages. 

wasi and witx are designed for describing interfaces to the OS/system and is not intended for general inter-module linking.

**Comment by promethe42** [comment]
> If you are generally trying to achieve inter-module calls or RPC between modules, I don't think you need WASI. You can either just use raw wasm types or follow the interface types proposal
> ...
> wasi and witx are designed for describing interfaces to the OS/system and is not intended for general inter-module linking.

Thank you! That's probably it yes. Somehow, WITX and Interface Types were the same thing to me.

I'll investigate Interface Types further.

The WITX format spec is still a worth some clarifications though.

**Comment by pchickey** [comment]
Hi - I implemented the `witx` crate, and a handful of the tools out there that consume it.

The witx language does not have a specification, except for the implementation of the `witx` crate. This is partly because we haven't gotten around to writing anything else, and partly because the language is a moving target. We intend for it to be based on interface types one day, but at the moment it is not, though it does borrow some syntax.

Witx today describes a C ABI. The `typename` declarations of structs, unions, arrays etc do not describe an abstract type like they would in interface types, but instead prescribe an in-memory representation that matches clang's wasm32 ABI. (The `witx` crate can calculate the layout, and when we introduced that code, I tested a large number of randomly-generated schemas to check that the `witx` calculations match clang's.) Another major difference between the witx language and interface types is that Witx contains `(@witx pointer ...)` and `(@witx const_pointer ...)` - these are concessions we require to describe the WASI ABI as it exists today.

When interface types is ready enough to have usable implementations, we will start figuring out how to evolve the Witx language and WASI specification to be based on interface types. However, this is going to be a major move that will definitely end up breaking compatibility with any tools that currently understand the Witx language. At the moment, we are not actively working on that.

Witx language descriptions of an interface could be automatically created from code like your Rust proc macro example, but presently all systems that consume Witx treat a human-authored Witx description as the canonical description of an interface. There is a small but growing ecosystem of code generators that consume Witx and emit boilerplate for various target languages - three I help maintain are https://github.com/WebAssembly/wasi-libc/tree/master/tools/wasi-headers generates the C header of all the types and import functions for `wasi-libc`, https://github.com/bytecodealliance/wasi/tree/main/crates/generate-raw is the morally equivalent generator for the Rust module used in the Rust `wasi` crate, and https://github.com/bytecodealliance/wasmtime/tree/main/crates/wiggle is a code generator for the host-side implementations of a witx interface used by `wasmtime` and `lucet`. You may wish to use some of these tools, especially `wiggle` which takes care of a big piece of the serialization/deserialization problem in the context of `wasmtime`.

**Comment by linclark** [comment]
To summarize for any new folks coming to this issue: Once the Interface Types proposal is finalized, we'll be putting work into more formally defining WITX.

I'm going to close this one out, because the evolution of WITX will be captured in other issues.

**Comment by sunfishcode** [comment]
To anyone who finds this issue looking for explanation of what WITX is:

At the time of this issue, "Wit" referred to a theoretical format which might be described as "[Wat](https://developer.mozilla.org/en-US/docs/WebAssembly/Understanding_the_text_format) but without the function bodies". That by itself wasn't very useful, so we created "Witx", adding features to make it at least somewhat usable for describing interfaces.

But even with the extra features, Witx still had many limitations. It wasn't good at generating bindings for any language other than C. It made virtualization awkward. It exposed language implementation details like 32-bit vs. 64-bit memory vs. wasmGC, which would lead to ecosystem incompatibilities.

And so, a new language was built, which we now call [Wit](https://github.com/WebAssembly/component-model/blob/main/design/mvp/WIT.md). Wit is designed from the start to be an Interface Definition Language, and by now it's seen a *lot* more development and the tooling for it is much more advanced. And this Wit is now what [WASI uses to define its interfaces]https://github.com/WebAssembly/WASI/tree/main/preview2#wasi-preview-2).
