### ISSUE TITLE
future consideration for file descriptors once we have reference-types

### ISSUE THREAD

**Issue by wanderer** [WebAssembly/WASI#34]
I think ideally we could represent file descriptors as an `anyref` once we have [reference-types](https://github.com/WebAssembly/reference-types). For the preopened file descriptors we could designate an `anyref` table which would be exported to load the references into. `fd_renumber` could be deprecated and `table.set/get` could be used instead. 

Using a table might also affect how preopened fd's are inherited by forking. Instead of forking there it might be nice to have a something that is tied more closely to wasm like `module.instantiate -> modRef`  The parent processes then could populate the preopened file descriptors table before calling the entry point function.

**Comment by tschneidereit** [comment]
That is indeed the plan for how to expose file descriptors and any other capabilities to Wasm modules, yes. See [the April 2 CG meeting notes](https://github.com/WebAssembly/meetings/blob/master/2019/CG-04-02.md#discuss-starting-a-new-cg-subgroup-for-wasi) for a conversation between @titzer and @sunfishcode about this topic.

**Comment by sunfishcode** [comment]
This is now implemented! Witx now includes a `(handle)` type, and the ephemeral branch is now using it to identify file descriptors instead of plain `i32`. It lowers to `i32` in the C bindings, but it's conceptually an index into a table of handles, as described in the [design principles](https://github.com/WebAssembly/WASI/blob/master/docs/DesignPrinciples.md#capability-based-security) document, and in the future when more support for reference types is available, we can create bindings that use reference types directly.
