### ISSUE TITLE
Unable to join meeting

### ISSUE THREAD

**Issue by syrusakbary** [WebAssembly/WASI#349]
Today I’ve been trying to join the WASI meeting using the Zoom link in the official WASI calendar invite.

```
The agenda and other meeting information is linked to from https://github.com/WebAssembly/WASI/tree/master/meetings/README.md.


Zoom meeting instructions:

Meeting ID: 912 0998 1546
https://mozilla.zoom.us/j/91209981546
One tap mobile
+13017158592,,91209981546# US (Germantown)
+13126266799,,91209981546# US (Chicago)
```

However, all my attempts to join were unsuccessful (at 9am, 9:05am and 9:15am -Zoom Error code: 1001).

Did the Zoom link changed for the meetings?

**Comment by tschneidereit** [comment]
The Zoom link didn't change, but it should have: I was the owner of the event temporarily until Dan's new work email got activated and he, as a chair, could be owner of the calendar event again. Unfortunately I missed the window to transfer ownership back to him and update the Zoom link, which is still associated with my now-defunct Mozilla account.

I've now transferred ownership back to Dan, who will update the invite before the next meeting. I'll follow up here and close the issue once the invite has been updated.

My apologies for the disruption and confusion this caused members of the subgroup!

**Comment by syrusakbary** [comment]
No worries. I guess no one was able to join today, mistakes happen.

I assume the WASI calendar invite will have the correct link for the next meeting, but otherwise please post here the link here so we are able to join the next WASI meeting. Thanks!

> PS: keeping the issue open until the meeting is updated with the working link

**Comment by yagehu** [comment]
Just want to piggyback off of this thread because I've been wondering for a while: How can I as an interested individual attend WASI meetings and just listen in? I remember reading somewhere that it's not open to public. But I couldn't find out how to gain access.

**Comment by tschneidereit** [comment]
The Zoom link has now been updated in the invite.

As a note, please don't publish the Zoom link going forward: we have to make sure that only members of the WebAssembly CG attend meetings, so we can't post a link to the calls publicly. This is required by the W3C to ensure compliance with contribution policies, e.g. around IP.

@yagehu, I just checked the docs and there's no good set of instructions for joining the calls, so we need to fix that. To get you sorted for now, please make sure you're [signed up to the CG](https://www.w3.org/community/webassembly/) and then send me an email to tschneidereit@[my_employer.com] and I'll get you invited.

I'll close this issue, since the original topic has been addressed.
