### ISSUE TITLE
Witx does not allow non-primitive error types

### ISSUE THREAD

**Issue by Ekleog** [WebAssembly/WASI#372]
The title says it all. Objective is being able to return `anyhow::Error` by storing its context backtrace in an `(array string)` (and maybe its stack backtrace in another).

A few pearls of wisdom out of @pchickey (thank you so much!):
- Currently development for non-primitive error types is blocked on wasm interface types actually happening
- `UserErrorConversion` can be used to log the error, or even to store it in the context as an `Option<Error>` so that a `last_error` function can be implemented that returns the non-primitive error.
- Alternatively, it could store in a `HashMap` and have the error primitive type be an index into that hashmap

**Comment by Ekleog** [comment]
Correction: actually, it turns out that (as far as I can find) a function can basically not return arrays or strings.

The workaround I use thus has to replace `last_error` that'd return the full `(array string)` result, by a `last_error_cause` that takes a mutable buffer to store the latest cause (returning the size written), and then unwraps just one layer of the error.

**Comment by sunfishcode** [comment]
Yeah, the few functions we have which return strings, such as `path_readlink`, do so by awkwardly passing pointers to buffers around. The difficulty is, as soon as we introduce dynamically-sized data, we need to figure out how to allocate it and how to manage its lifetime. There are ways we could imagine solving this, however they quickly get complex, error-prone, and/or difficult to do in source-language-agnostic ways. [Interface types](https://github.com/WebAssembly/interface-types) will give us the tools to solve these problems in much more comprehensive ways.

**Comment by linclark** [comment]
As Dan noted above, once interface types has advanced, this will be possible. That's orthogonal to WASI's development, so I'm going to close this one out. 

One thing to note: while we're happy to support non-primitive error types, we would generally prefer that APIs not return string error messages. This is partly because of localization issues, and partly because strings are harder for consuming code to use e.g. we don't want developers to have to do string comparison to make decisions based on the returned error.
