### ISSUE TITLE
Integration of streams

### ISSUE THREAD

**Issue by badeend** [WebAssembly/WASI#486]
In POSIX, the resource handle _is_ the stream. The stream is manipulated chunk-wise using `read` & `write`.

In the Component Model, resources and streams are separate. How do you envision `stream` s being incorporated into WASI API's?

The most POSIX-ish implementation I could come up with is something like the following, where every chunk is a separate stream:

```
resource my-fd-like {
	read: func(bytes-to-read: u32) -> expected<stream<u8, _>, ...>
	write: func(chunk: stream<...>) -> expected<_, ...>
}
```

But, conceptually the entire fd represents a single stream, so using a new `stream` per chunk feels like swimming against the "stream" to me.

Though, based on his presentation, it seems Luke _does_ intend it to be used like this:

![image](https://user-images.githubusercontent.com/3646561/177041781-c7c3931c-0c74-480a-8879-5bfa212849f0.png)

---

The programming languages that have built-in streams (that I'm familiar with) generally use a one-stream-per-file-descriptor approach:

```
resource my-fd-like {
	get-input-stream: func() -> stream<...> // readable stream
	get-output-stream: func() -> stream<...> // writeable stream

	// or:

	get-stream: func() -> stream<...> // readable+writable stream
}
```

But I currently don't see how to build a POSIX-compatible layer on top of this.

---

Blocks: https://github.com/bytecodealliance/wasmtime/issues/4276

**Comment by badeend** [comment]
In the updated filesystem API, does `(p)read` return a stream to the end of the file, rather than a single chunk?
Also, does `(p)write`'s future only resolve after the input stream has been completely consumed (or an error has occurred)?

**Comment by sunfishcode** [comment]
Yes, the current `pread` returns a stream to the end of the file. We could change that; we could have `pread` take a size, and then return a stream that stops when it reaches that size. I think we can make the user-facing libc `pread` API work on top of either form though, so I don't have a clear sense of which is best.

Also, yes, the current `pwrite`'s future resolves after the stream has been closed, successfully or otherwise.

**Comment by sunfishcode** [comment]
In general, WASI's answers to many of these questions, such as the design of streams, are answered by the Wasm [component model](https://github.com/WebAssembly/component-model), so that would be a good place to follow up for more detailed discussion.

Sharing a bare virtual-memory object may simplify some optimizations, but it requires a great degree of coordination between components, to line up on synchronization, data representation, and data lifetimes, so it isn't a great fit for WASI's goals for isolation and cross-language interoperability. It also exposes a lot of information about how the host OS kernel works, which may be ok if the platform will always work the way Zircon does, but is less natural to do in all the environments that WASI is aiming to be useful in.

WASI's streams will be capable of zero-copy I/O with the host. Initially, component-to-component streams will require a copy. That said, there are some ideas in flight about ways to avoid the overhead of the copy in situations where it's significant.

**Comment by sunfishcode** [comment]
I think what we want to do here is remove `read` and `write` from files, and just have `pread` and `pwrite` which create new streams at the given offset. For sockets, I think your draft PR looks good.

My current thinking is that file descriptors will be a libc-level concept, so libc will handle mapping random-access requests to the wasi-filesystem API or to other APIs as needed, and returning `ESPIPE` or so for attempts to do random-access on sockets.

**Comment by badeend** [comment]
> For sockets, I think your draft PR looks good.

I've updated and published the PR. Now one can only call the streaming functions exactly once. This makes for a conceptually easier interface. Also, it allows to hook up the closing of a stream to the `shutdown` syscall.

---

> I think what we want to do here is remove read and write from files, and just have pread and pwrite which create new streams at the given offset.

Seems reasonable. 

Side note: The "p" prefix exists to differentiate it between the regular read/write calls. If you drop the "p"-less variants, there is no confusion left between the two, so then we could rename `pread` to `read`.

**Comment by sascha1337** [comment]
Hopium confirmed

**Comment by badeend** [comment]
> Hopium confirmed

I don't know what that means.
