### ISSUE TITLE
Does Function that return buffer with string  should include trailling 0 or not

### ISSUE THREAD

**Issue by ptitSeb** [WebAssembly/WASI#492]
There are a few functions, like `fd_prestat_dir_name` or `fd_readdir` that fill in buffer with string representing file names. The specs doesn't precised is the buffer include or not the trailling zero.  What should it be? with or without the trailling 0?

**Comment by syrusakbary** [comment]
Can this be added as point of discussion for the next WASI meeting @linclark?

We'd like to know which way is the proper one to make sure the Wasmer WASI implementation respect the specs, and right now is not clear on what the official way is

**Comment by linclark** [comment]
@syrusakbary please follow the procedure for adding a discussion topic (adding a PR to the agenda in the meetings repo)

**Comment by syrusakbary** [comment]
Here we go: https://github.com/WebAssembly/meetings/pull/1094

**Comment by sunfishcode** [comment]
wasi-libc has code [for fd_prestat_dir_name](https://github.com/WebAssembly/wasi-libc/blob/dcd28cf8f6db612d8f71f2f9ca6bb6b4e46451b8/libc-bottom-half/sources/preopens.c#L247) and [fd_readdir](https://github.com/WebAssembly/wasi-libc/blob/7302f33f99233482de8eedfcd21495c20858e0e4/libc-bottom-half/cloudlibc/src/libc/dirent/readdir.c#L83) to insert trailing NUL's in the places where it needs them to be.

In languages other than C, strings aren't usually NUL-terminated, so [their use of `fd_readdir` doesn't need a trailing 0](https://github.com/rust-lang/rust/blob/master/library/std/src/sys/wasi/fs.rs#L226).

Consequently, I propose Wasmtime's current behavior in these two instances be considered the correct behavior.

**Comment by linclark** [comment]
@ptitSeb It might be good to have some context on what you're trying to do, as that will help understand what exact information you need.

You're right that strings aren't defined in WASI. That is by design. Instead of having a concrete definition of strings in WASI, there is an abstract string type, and that is defined in a different part of the WebAssembly standards, the component model.

As stated in the README, we are currently in the process of switching from the initial `witx` to `wit`, which is what the component model is defining. 

> WASI is transitioning away from the witx format and its early experimental ABI. We are transitioning to Interface Types using the wit format and the canonical ABI. 

If you want to learn more about the thinking behind these types, you can read [this post](https://hacks.mozilla.org/2019/08/webassembly-interface-types/) or dig into the [component model repo](https://github.com/WebAssembly/component-model).

**Comment by ptitSeb** [comment]
I'm trying to maintain a wasi implementation.

But the spec are still not completely consistant. For example, the `args_get` and `environ_get` function does precise that string buffer returned are 0 terminated. But not for `fd_prestat_dir_name` or `fd_readdir` where it's not precised.
Similarité, the `path_create_directory` function, the string is not defined as 0 terminated, but it must be there.
Basicaly, most function involving string needs 0-terminated string except those 2.

I dug a bit the component model, but the only thing I found bout string is "list of char" which is still not precise on how you delimit the end of the string (sized or 0-terminated).

**Comment by ptitSeb** [comment]
Yeah, so basically, If I sum-up:

* string are a tuple, pointer + size
* Unless stated otherwise, Inputed strings are NOT 0-terminated (because they are sized).
* Unless stated otherwise, returned string buffer doesn't contains a 0 char at end of string.
