### ISSUE TITLE
__wasi_prestat_t documentation is missing

### ISSUE THREAD

**Issue by wanderer** [WebAssembly/WASI#51]
the description of `__wasi_prestat_t` from [`__wasi_fd_prestat_get`](https://github.com/WebAssembly/WASI/blob/master/design/WASI-core.md#__wasi_fd_prestat_get) seems to missing.  Its defined [here](https://github.com/CraneStation/wasmtime/blob/3e94af81df7c34b2e2cfd78482b740b80a2ec1fe/wasmtime-wasi/sandboxed-system-primitives/include/wasmtime_ssp.h#L310) in wasmtime but I'm not sure why  `__wasi_preopentype_t pr_type;` can't just be a `__wasi_filetype_t`

**Comment by sunfishcode** [comment]
This was fixed in c760e95483c357dd814984bba85c2be1c97c3252.

`pr_type` isn't a `__wasi_filetype_t` because in the future we may have more kinds of preopen types, like [preopened clocks](https://github.com/WebAssembly/WASI/issues/118) or other things. We could stand to have [more preopen types than we do now](https://github.com/WebAssembly/WASI/issues/91) though.
