### ISSUE TITLE
Up-to-date ABI definition?

### ISSUE THREAD

**Issue by tareksander** [WebAssembly/WASI#568]
There are the [Preview 1](https://github.com/WebAssembly/WASI/blob/main/legacy/preview1/docs.md) type and function definitions, but they don't translate directly into an ABI. Is the [wasi.h](https://github.com/WebAssembly/wasi-libc/blob/main/libc-bottom-half/headers/public/wasi/api.h) header in the WASI libc the current ABI?

I want to create my own implementation so I can use it in wasmtime on desktop and the browser API on the web.

**Comment by alterstep** [comment]
https://wasix.org/docs/api-reference

**Comment by alterstep** [comment]
WASI for web browsers -------> https://www.npmjs.com/package/@wasmer/wasi

**Comment by pchickey** [comment]
For preview 1 ABIs, the definitions at https://github.com/WebAssembly/WASI/blob/main/legacy/preview1/docs.md describe all of the types and their internal layouts, which is sufficient to describe the ABI. That same information is consumed, programmatically via the `witx` crate, by Wasmtime's `wiggle` crate for generating safe bindings to witx interfaces. You might find that using the `witx` crate directly, rather than what it renders into markdown or html, is better for some needs.

For preview 2 interfaces, you want to instead look at the component-model spec on canonical ABI and the wit-bindgen family of generators for building implementations.

**Comment by tareksander** [comment]
Ah thanks, the `wiggle` crate looks perfect, I'm using Rust anyways. That means I won't even have to manually translate the definitions.

Is there a timeline for preview 2 and the component model? They seem like a better fit, but I don't know if anything supports it yet.

**Comment by pchickey** [comment]
We are in the end stages of stabilizing the Preview 2 definitions, and their implementations in Wasmtime and jco, as well as supporting software such as wasm-tools, wit-bindgen, etc right now. We expect Preview 2 to be tagged in December 2023 or January 2024.

**Comment by tareksander** [comment]
Oh, I didn't realize there has been so much progress. I might wait for preview 2 and the component model then. How usable is the component model in wasmtime right now, and can wit-bindgen produce host and guest bindings in Rust? If yes, I can already start before the complete stabilization, I don't mind having to make a few changes if needed for the final version.

**Comment by pchickey** [comment]
Everything is working pretty well for the last two or three wasmtime releases, but the wit definitions of what WASI is have been changing. If you are willing to deal with a little bit more churn there, I would recommend adopting the Preview 2 work-in-progress now instead of using witx abis, because the wit tooling is in general much, much better than anything from the witx era.

**Comment by tareksander** [comment]
As long as the wit tooling is stable it's good for me, it'd be quite a while before I need to compile something depending on WASI anyways, but I'd also like to use wit for my own interfaces. Where can I find the current wit tools?

**Comment by pchickey** [comment]
Here are some good docs to get started: https://component-model.bytecodealliance.org/. You can also ask questions in the bytecodealliance discord to get more help

**Comment by pchickey** [comment]
I'm going to close this as resolved, please re-open if there are any outstanding questions.
