### ISSUE TITLE
dl_open + dl_sym + dl_error + dl_close

### ISSUE THREAD

**Issue by brandonros** [WebAssembly/WASI#84]
It'd be super neat if WASI was extended to define any variation of:

* `void *dlopen(const char *filename, int flag);`

* `char *dlerror(void);`

* `void *dlsym(void *handle, const char *symbol);`

* `int dlclose(void *handle);`

Some discussion was held in https://github.com/WebAssembly/WASI/issues/68

This would allow WASM modules to interact with system level libraries and build powerful things like native GUIs, etc.

Windows could be handled with something like https://github.com/node-ffi/node-ffi/blob/master/src/win32-dlfcn.cc

**Comment by brandonros** [comment]
Would we need a `dl_call` that accepts a `dlopen handle` + a `dlsym symbol` + an array of arguments of different types (structs, pointers, etc.)?

**Comment by sbc100** [comment]
I was assuming we were talking about dl_open of other WASI libs.    At least I think that dynamic linking between WASI module (include runtime loading) should be considered separately to being able to access host DLLs.  I imagine the former will be relatively uncontroversial, the later might not make as much sense in WASI especially because of the security implications.

**Comment by brandonros** [comment]
>  the later might not make as much sense in WASI especially because of the security implications.

While I don't disagree whatsoever, I'm curious what it would take in your eyes to empower WASM runtimes to every support accessing host DLLs / how you see that panning out.

Is that just not in the cards for WASM at this time?

**Comment by MarkMcCaskey** [comment]
I think this feature has to be outside of the Wasm module.  Letting Wasm modules execute arbitrary native code is impossible to secure.  Something that might make sense is to have the host system have a whitelist of native functions (that the user can edit) and that the Wasm module can use.

The issue with that is that it wouldn't be portable.  Having a native-emulation layer seems like a more promising route for the general use case, as I understand it.  What I mean is that if you have a Windows application that is using Windows-APIs, compiling that to something portable that may produce the same output on Windows but also has the same or comparable output on other systems.

As discussed in the Wasmer issue, a way to get something like this working sooner without modifying an existing runtime is to use a client-server architecture with the non-portable, direct system access on the client and your portable logic on the server running in Wasm.  That's isomorphic to what modifying a runtime does, just using sockets or ipc or something instead of imports.

**Comment by brandonros** [comment]
> Letting Wasm modules execute arbitrary native code is impossible to secure.

It is, but it is not impossible to put behind a "execute_arbitrary_native_code" opt-in permission/right.

**Comment by sunfishcode** [comment]
This discussion is getting fairly off topic here. We've established that `dlopen` etc. of wasm libraries is desirable functionality in WASI, though there is tooling and design work outside of WASI needed to support this.

**Comment by jgravelle-google** [comment]
I wouldn't say it's off topic, my understanding is this specific issue was raised with native code specifically in mind, #68 was more focused on dlopen for wasm libraries.

However I don't think executing native code is a generally desirable property for WASI. It's sufficiently at odds with the rest of the design that I don't know if it's productive discussion fodder.

**Comment by brandonros** [comment]
> However I don't think executing native code is a generally desirable property for WASI. It's sufficiently at odds with the rest of the design that I don't know if it's productive discussion fodder.

While I do agree with this sentiment, I am interested to hear where in the WebAssembly ecosystem executing native code falls in your mind. The answer may very well be "just not planned / a priority at this time" and I could be barking up a tree that makes no sense.

There are a couple of different routes to do it, obviously. Native non-standard runtime extensions / plugins come into mind, but my followup question then would be: why not standardize it?

I think a lot of node.js's success was because of how early on it made cross-platform native module bundling. Obviously WebAssembly isn't trying to be node.js or compete with node.js, but with the interest in "WebAssembly running out of browser", I feel like the "how to execute native code" question should be answered/outlined/discussed?

**Comment by MikeInnes** [comment]
Is it worth splitting this into explicit issues for (1) `dlopen`ing WASM modules and (2) calling native code?

Given the inherent security and OS-dependence issues of calling native code, I understand it may not be a good fit for WASI core. But something like it seems inevitable given the number of important use cases which are infeasible otherwise (e.g. using IPC). While it's straightforward to do something ad-hoc with an existing runtime, it'd be nice to understand how this could fit in well with WASI's current design and security model, if at all (e.g. each trusted DLL+WITX as a capability?).

**Comment by brandonros** [comment]
> (1) dlopening WASM modules

What real world use case can you come up with for this given that a WASM module by itself isn't capable of interacting with anything that isn't defined and injected through its runtime?

**Comment by sbc100** [comment]
> > (1) dlopening WASM modules
> 
> What real world use case can you come up with for this given that a WASM module by itself isn't capable of interacting with anything that isn't defined and injected through its runtime?

Most plugin architectures that I know of use dlopen (or equivalent) to load plugins at runtime.  For example a video player, with plug-able decoders. 

Or applications that want to start running while other parts download in the background and the load them in on demand.

**Comment by linclark** [comment]
I'm going to close this one out. Dynamically loading libraries is a thing we want to do, but running host dlls directly implies a bunch of extra functionality that is out of scope.
